[workspace]
members = [
    "darkproto",
    "darkproto-enclave-streaming",
    "threshold-crypto",
]
exclude = [
    "aes-primitives",
    "aes-benchmarks",
    "block-ciphers",
    "AEADs",
    "stream-ciphers",
    "RSA",
    "elliptic-curves",
]
