in_file = "./.dl/bbb_sunflower_native_60fps_stereo_abl.mp4"
out_enc_file = "./.dl/bbb_sunflower_native_60fps_stereo_abl.mp4.encrypted"
out_re_enc_file = "./.dl/bbb_sunflower_native_60fps_stereo_abl.mp4.re_encrypted"
init_enc_pwd_file = "./.vault/pwd"
re_enc_pwd_file = "./.vault/re_enc_pwd"
init_random_seed_file = "./.vault/seed"
re_enc_random_seed_file = "./.vault/re_enc_seed"
enc_cipher_algo = "chacha20"
re_enc_cipher_algo = "chacha20"
